name: test

on:
  [push, pull_request]

jobs:
  build:
    environment: testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
    - name: black check
      run: |
        black --check push_to_gdoc tests/
    - name: Test with pytest
      env: 
        PUSH_TO_GDOCS_SERVICE_CREDS: ${{ secrets.PUSH_TO_GDOCS_SERVICE_CREDS }}
      run: |
        pytest
